export const FETCH_ALL_PRODUCTS = "products/FETCH_ALL_PRODUCTS";
export const REQUEST_ALL_PRODUCTS = "products/REQUEST_ALL_PRODUCTS";
export const REQUEST_ALL_PRODUCTS_ERROR = "products/REQUEST_ALL_PRODUCTS_ERROR";
export const REQUEST_ALL_PRODUCTS_SUCCESS =
  "products/REQUEST_ALL_PRODUCTS_SUCCESS";

export const FETCH_CREATE_PRODUCT = "products/FETCH_CREATE_PRODUCT";
export const REQUEST_CREATE_PRODUCT = "products/REQUEST_CREATE_PRODUCT";
export const REQUEST_CREATE_PRODUCT_ERROR =
  "products/REQUEST_CREATE_PRODUCT_ERROR";
export const REQUEST_CREATE_PRODUCT_SUCCESS =
  "products/REQUEST_CREATE_PRODUCT_SUCCESS";

export const FETCH_DELETE_PRODUCT = "products/FETCH_DELETE_PRODUCT";
export const REQUEST_DELETE_PRODUCT = "products/REQUEST_DELETE_PRODUCT";
export const REQUEST_DELETE_PRODUCT_SUCCESS =
  "products/REQUEST_DELETE_PRODUCT_SUCCESS";
export const REQUEST_DELETE_PRODUCT_ERROR =
  "products/REQUEST_DELETE_PRODUCT_ERROR";

export const FETCH_SINGLE_PRODUCT = "products/FETCH_SINGLE_PRODUCT";
export const REQUEST_SINGLE_PRODUCT = "products/REQUEST_SINGLE_PRODUCT";
export const REQUEST_SINGLE_PRODUCT_ERROR =
  "products/REQUEST_SINGLE_PRODUCT_ERROR";
export const REQUEST_SINGLE_PRODUCT_SUCCESS =
  "products/REQUEST_SINGLE_PRODUCT_SUCCESS";

export const FETCH_UPDATE_PRODUCT = "products/FETCH_UPDATE_PRODUCT";
export const REQUEST_UPDATE_PRODUCT = "products/REQUEST_UPDATE_PRODUCT";
export const REQUEST_UPDATE_PRODUCT_ERROR =
  "products/REQUEST_UPDATE_PRODUCT_ERROR";
export const REQUEST_UPDATE_PRODUCT_SUCCESS =
  "products/REQUEST_UPDATE_PRODUCT_SUCCESS";
