export const FETCH_ALL_SUB_CATEGORY = "sub_category/FETCH_ALL_SUB_CATEGORY";
export const REQUEST_ALL_SUB_CATEGORY = "sub_category/REQUEST_ALL_SUB_CATEGORY";
export const REQUEST_ALL_SUB_CATEGORY_ERROR =
  "sub_category/REQUEST_ALL_SUB_CATEGORY_ERROR";
export const REQUEST_ALL_SUB_CATEGORY_SUCCESS =
  "sub_category/REQUEST_ALL_SUB_CATEGORY_SUCCESS";

export const FETCH_DELETE_SUB_CATEGORY =
  "sub_category/FETCH_DELETE_SUB_CATEGORY";
export const REQUEST_DELETE_SUB_CATEGORY =
  "sub_category/REQUEST_DELETE_SUB_CATEGORY";
export const REQUEST_DELETE_SUB_CATEGORY_ERROR =
  "sub_category/REQUEST_DELETE_SUB_CATEGORY_ERROR";
export const REQUEST_DELETE_SUB_CATEGORY_SUCCESS =
  "sub_category/REQUEST_DELETE_SUB_CATEGORY_SUCCESS";

export const FETCH_CREATE_SUB_CATEGORY =
  "sub_category/FETCH_CREATE_SUB_CATEGORY";
export const REQUEST_CREATE_SUB_CATEGORY =
  "sub_category/REQUEST_CREATE_SUB_CATEGORY";
export const REQUEST_CREATE_SUB_CATEGORY_ERROR =
  "sub_category/REQUEST_CREATE_SUB_CATEGORY_ERROR";
export const REQUEST_CREATE_SUB_CATEGORY_SUCCESS =
  "sub_category/REQUEST_CREATE_SUB_CATEGORY_SUCCESS";

export const FETCH_EDIT_SUB_CATEGORY = "sub_category/FETCH_EDIT_SUB_CATEGORY";
export const REQUEST_EDIT_SUB_CATEGORY =
  "sub_category/REQUEST_EDIT_SUB_CATEGORY";
export const REQUEST_EDIT_SUB_CATEGORY_ERROR =
  "sub_category/REQUEST_EDIT_SUB_CATEGORY_ERROR";
export const REQUEST_EDIT_SUB_CATEGORY_SUCCESS =
  "sub_category/REQUEST_EDIT_SUB_CATEGORY_SUCCESS";

export const FETCH_SINGLE_SUB_CATEGORY =
  "sub_category/FETCH_SINGLE_SUB_CATEGORY";
export const REQUEST_SINGLE_SUB_CATEGORY =
  "sub_category/REQUEST_SINGLE_SUB_CATEGORY";
export const REQUEST_SINGLE_SUB_CATEGORY_ERROR =
  "sub_category/REQUEST_SINGLE_SUB_CATEGORY_ERROR";
export const REQUEST_SINGLE_SUB_CATEGORY_SUCCESS =
  "sub_category/REQUEST_SINGLE_SUB_CATEGORY_SUCCESS";
