export const FETCH_ALL_PROMOCODES = "promocode/FETCH_ALL_PROMOCODES";
export const REQUEST_ALL_PROMOCODES = "promocode/REQUEST_ALL_PROMOCODES";
export const REQUEST_ALL_PROMOCODES_ERROR =
  "promocode/REQUEST_ALL_PROMOCODES_ERROR";
export const REQUEST_ALL_PROMOCODES_SUCCESS =
  "promocode/REQUEST_ALL_PROMOCODES_SUCCESS";

export const FETCH_DELETE_PROMOCODE = "promocode/FETCH_DELETE_PROMOCODE";
export const REQUEST_DELETE_PROMOCODE = "promocode/REQUEST_DELETE_PROMOCODE";
export const REQUEST_DELETE_PROMOCODE_ERROR =
  "promocode/REQUEST_DELETE_PROMOCODE_ERROR";
export const REQUEST_DELETE_PROMOCODE_SUCCESS =
  "promocode/REQUEST_DELETE_PROMOCODE_SUCCESS";

export const FETCH_CREATE_PROMOCODE = "promocode/FETCH_CREATE_PROMOCODE";
export const REQUEST_CREATE_PROMOCODE = "promocode/REQUEST_CREATE_PROMOCODE";
export const REQUEST_CREATE_PROMOCODE_ERROR =
  "promocode/REQUEST_CREATE_PROMOCODE_ERROR";
export const REQUEST_CREATE_PROMOCODE_SUCCESS =
  "promocode/REQUEST_CREATE_PROMOCODE_SUCCESS";

export const FETCH_SINGLE_PROMOCODE = "promocode/FETCH_SINGLE_PROMOCODE";
export const REQUEST_SINGLE_PROMOCODE = "promocode/REQUEST_SINGLE_PROMOCODE";
export const REQUEST_SINGLE_PROMOCODE_ERROR =
  "promocode/REQUEST_SINGLE_PROMOCODE_ERROR";
export const REQUEST_SINGLE_PROMOCODE_SUCCESS =
  "promocode/REQUEST_SINGLE_PROMOCODE_SUCCESS";

export const FETCH_UPDATE_PROMOCODE = "promocode/FETCH_UPDATE_PROMOCODE";
export const REQUEST_UPDATE_PROMOCODE = "promocode/REQUEST_UPDATE_PROMOCODE";
export const REQUEST_UPDATE_PROMOCODE_ERROR =
  "promocode/REQUEST_UPDATE_PROMOCODE_ERROR";
export const REQUEST_UPDATE_PROMOCODE_SUCCESS =
  "promocode/REQUEST_UPDATE_PROMOCODE_SUCCESS";
