export const FETCH_ALL_CATEGORIES = "categories/FETCH_ALL_CATEGORIES";
export const REQUEST_ALL_CATEGORIES = "categories/REQUEST_ALL_CATEGORIES";
export const REQUEST_ALL_CATEGORIES_SUCCESS =
  "categories/REQUEST_ALL_CATEGORIES_SUCCESS";
export const REQUEST_ALL_CATEGORIES_ERROR =
  "categories/REQUEST_ALL_CATEGORIES_ERROR";

export const FETCH_DELETE_CATEGORY = "categories/FETCH_DELETE_CATEGORY";
export const REQUEST_DELETE_CATEGORY = "categories/REQUEST_DELETE_CATEGORY";
export const REQUEST_DELETE_CATEGORY_ERROR =
  "categories/REQUEST_DELETE_CATEGORY_ERROR";
export const REQUEST_DELETE_CATEGORY_SUCCESS =
  "categories/REQUEST_DELETE_CATEGORY_SUCCESS";

export const FETCH_CREATE_CATEGORY = "categories/FETCH_CREATE_CATEGORY";
export const REQUEST_CREATE_CATEGORY = "categories/REQUEST_CREATE_CATEGORY";
export const REQUEST_CREATE_CATEGORY_SUCCESS =
  "categories/REQUEST_CREATE_CATEGORY_SUCCESS";
export const REQUEST_CREATE_CATEGORY_ERROR =
  "categories/REQUEST_CREATE_CATEGORY_ERROR";

export const FETCH_SINGLE_CATEGORY = "categories/FETCH_SINGLE_CATEGORY";
export const REQUEST_SINGLE_CATEGORY = "categories/REQUEST_SINGLE_CATEGORY";
export const REQUEST_SINGLE_CATEGORY_ERROR =
  "categories/REQUEST_SINGLE_CATEGORY_ERROR";
export const REQUEST_SINGLE_CATEGORY_SUCCESS =
  "categories/REQUEST_SINGLE_CATEGORY_SUCCESS";

export const FETCH_UPDATE_CATEGORY = "categories/FETCH_UPDATE_CATEGORY";
export const REQUEST_UPDATE_CATEGORY = "categories/REQUEST_UPDATE_CATEGORY";
export const REQUEST_UPDATE_CATEGORY_ERROR =
  "categories/REQUEST_UPDATE_CATEGORY_ERROR";
export const REQUEST_UPDATE_CATEGORY_SUCCESS =
  "categories/REQUEST_UPDATE_CATEGORY_SUCCESS";
