export const FETCH_CREATE_PHOTO = "images/FETCH_CREATE_PHOTO";
export const REQUEST_CREATE_PHOTO = "images/REQUEST_CREATE_PHOTO";
export const REQUEST_CREATE_PHOTO_ERROR = "images/REQUEST_CREATE_PHOTO_ERROR";
export const REQUEST_CREATE_PHOTO_SUCCESS =
  "images/REQUEST_CREATE_PHOTO_SUCCESS";
