export const FETCH_ALL_ORDERS = "orders/FETCH_ALL_ORDERS";
export const REQUEST_ALL_ORDERS = "orders/REQUEST_ALL_ORDERS";
export const REQUEST_ALL_ORDERS_ERROR = "orders/REQUEST_ALL_ORDERS_ERRORS";
export const REQUEST_ALL_ORDERS_SUCCESS = "orders/REQUEST_ALL_ORDERS_SUCCESS";

export const FETCH_SINGLE_ORDER = "orders/FETCH_SINGLE_ORDER";
export const REQUEST_SINGLE_ORDER = "orders/REQUEST_SINGLE_ORDER";
export const REQUEST_SINGLE_ORDER_ERROR = "orders/REQUEST_SINGLE_ORDER_ERROR";
export const REQUEST_SINGLE_ORDER_SUCCESS =
  "orders/REQUEST_SINGLE_ORDER_SUCCESS";

export const FETCH_UPDATE_ORDER_STATUS = "orders/FETCH_UPDATE_ORDER_STATUS";
export const REQUEST_UPDATE_ORDER_STATUS = "orders/REQUEST_UPDATE_ORDER_STATUS";
export const REQUEST_UPDATE_ORDER_STATUS_ERROR =
  "orders/REQUEST_UPDATE_ORDER_STATUS_ERROR";
export const REQUEST_UPDATE_ORDER_STATUS_SUCCESS =
  "orders/REQUEST_UPDATE_ORDER_STATUS_SUCCESS";
